import { DashboardData } from "./interface";

export const dashboardData: DashboardData = {
  summary: {
    totalMyDocuments: 12,
    draft: 2,
    waitingSignature: 1,
    inProgress: 4,
    completed: 4,
    rejected: 1,
    needMySignature: 3,
    overdue: 2,
  },
  urgent: [
    {
      id: "doc-uuid-001",
      title: "Kontrak Kerjasama PT Maju Bersama",
      fileName: "kontrak_pt_maju.pdf",
      documentStatus: "IN_PROGRESS",
      urgentType: "NEED_MY_SIGNATURE",
      ownerName: "budi.santoso",
      pendingContributors: null,
      deadline: "2025-04-07T23:59:00",
      isOverdue: false,
    },
    {
      id: "doc-uuid-002",
      title: "MOU Vendor Logistik 2025",
      fileName: "mou_vendor_logistik.pdf",
      documentStatus: "WAITING_SIGNATURE",
      urgentType: "WAITING_OTHERS",
      ownerName: "john.doe",
      pendingContributors: 2,
      deadline: "2025-04-06T23:59:00",
      isOverdue: true,
    },
    {
      id: "doc-uuid-003",
      title: "MOU Vendor Logistik 2025",
      fileName: "mou_vendor_logistik.pdf",
      documentStatus: "WAITING_SIGNATURE",
      urgentType: "WAITING_OTHERS",
      ownerName: "john.doe",
      pendingContributors: 2,
      deadline: "2025-04-06T23:59:00",
      isOverdue: true,
    },
    {
      id: "doc-uuid-004",
      title: "MOU Vendor Logistik 2025",
      fileName: "mou_vendor_logistik.pdf",
      documentStatus: "WAITING_SIGNATURE",
      urgentType: "WAITING_OTHERS",
      ownerName: "john.doe",
      pendingContributors: 2,
      deadline: "2025-04-06T23:59:00",
      isOverdue: true,
    },
  ],
  myActiveDocuments: [
    {
      id: "doc-uuid-003",
      title: "Perjanjian Sewa Gedung 2025",
      fileName: "perjanjian_sewa.pdf",
      fileSize: 204800,
      status: "IN_PROGRESS",
      folderName: "Kontrak 2025",
      totalContributors: 3,
      signedContributors: 1,
      pendingContributors: 2,
      deadline: "2025-04-20T23:59:00",
      isOverdue: false,
      updatedAt: "2025-04-03T08:30:00",
    },
    {
      id: "doc-uuid-004",
      title: "Surat Penunjukan Vendor IT",
      fileName: "surat_penunjukan_it.pdf",
      fileSize: 153600,
      status: "WAITING_SIGNATURE",
      folderName: null,
      totalContributors: 2,
      signedContributors: 0,
      pendingContributors: 2,
      deadline: "2025-04-15T23:59:00",
      isOverdue: false,
      updatedAt: "2025-04-02T14:00:00",
    },
    {
      id: "doc-uuid-006",
      title: "Perjanjian Sewa Gedung 2025",
      fileName: "perjanjian_sewa.pdf",
      fileSize: 204800,
      status: "IN_PROGRESS",
      folderName: "Kontrak 2025",
      totalContributors: 3,
      signedContributors: 1,
      pendingContributors: 2,
      deadline: "2025-04-20T23:59:00",
      isOverdue: false,
      updatedAt: "2025-04-03T08:30:00",
    },
  ],
  recentActivity: [
    {
      documentId: "doc-uuid-003",
      documentTitle: "Perjanjian Sewa Gedung 2025",
      activityType: "CONTRIBUTOR_SIGNED",
      description: "siti.rahma menandatangani dokumen",
      triggeredBy: "siti.rahma",
      createdAt: "2025-04-03T08:30:00",
    },
    {
      documentId: "doc-uuid-005",
      documentTitle: "Kontrak Freelance Desainer",
      activityType: "CONTRIBUTOR_REJECTED",
      description:
        "andi.wijaya menolak dokumen: Data pihak kedua kurang lengkap",
      triggeredBy: "andi.wijaya",
      createdAt: "2025-04-02T16:45:00",
    },
    {
      documentId: "doc-uuid-004",
      documentTitle: "Surat Penunjukan Vendor IT",
      activityType: "STATUS_CHANGED",
      description: "Status dokumen berubah menjadi WAITING_SIGNATURE",
      triggeredBy: "john.doe",
      createdAt: "2025-04-02T14:00:00",
    },
    {
      documentId: "doc-uuid-005",
      documentTitle: "Surat Penunjukan Vendor IT",
      activityType: "STATUS_CHANGED",
      description: "Status dokumen berubah menjadi WAITING_SIGNATURE",
      triggeredBy: "john.doe",
      createdAt: "2025-04-02T14:00:00",
    },
    {
      documentId: "doc-uuid-006",
      documentTitle: "Surat Penunjukan Vendor IT",
      activityType: "STATUS_CHANGED",
      description: "Status dokumen berubah menjadi WAITING_SIGNATURE",
      triggeredBy: "john.doe",
      createdAt: "2025-04-02T14:00:00",
    },
    {
      documentId: "doc-uuid-007",
      documentTitle: "Surat Penunjukan Vendor IT",
      activityType: "STATUS_CHANGED",
      description: "Status dokumen berubah menjadi WAITING_SIGNATURE",
      triggeredBy: "john.doe",
      createdAt: "2025-04-02T14:00:00",
    },
  ],
};
