import NotificationStoreHydrator from "@/components/providers/NotificationStoreHydrator";
import SocketProvider from "@/components/providers/SocketProvider";
import AuthLayout from "@/components/templates/AuthLayout";
import { getNotificationServer } from "@/lib/api/notificationApi.server";
import { Notification } from "@/lib/types/notification";
import { PaginationResponse } from "@/lib/utils/interface";
import type { Metadata } from "next";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Signtify",
  description: "Generated by create next app",
};

export default async function Auth({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const paginationDefault = {
    totalPages: 0,
    totalElements: 0,
    page: 1,
    size: 10,
    hasNext: false,
    hasPrevious: false,
  };

  let initialNotifications: Notification[] = [];
  let initialPagination: PaginationResponse = paginationDefault;

  try {
    const data = await getNotificationServer("1", "5");
    initialNotifications = data?.data || [];
    initialPagination = data?.paginationResponse || paginationDefault;
  } catch {}

  return (
    <Providers>
      <NotificationStoreHydrator
        notifications={initialNotifications}
        pagination={initialPagination}
      />
      <AuthLayout>{children}</AuthLayout>
      <SocketProvider />
    </Providers>
  );
}
