import AuthLayout from "@/components/templates/AuthLayout";
import type { Metadata } from "next";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Signtify",
  description: "Generated by create next app",
};

export default function Auth({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <AuthLayout>{children}</AuthLayout>
    </Providers>
  );
}
